# Site settings
title: Where Is the Hide Button!?
email: sunzenshen@gmail.com
description: "Pardon the dust."
baseurl: ""
url: ""
twitter_username: sunzenshen
github_username:  sunzenshen

# Build settings
markdown: kramdown
permalink: pretty
