# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown


defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: "@sunzenshen"

title: "Alan Shen"
description: Pardon the dust.
author:
  name: Alan Shen
  email: sunzenshen@gmail.com
  github: sunzenshen
  twitter: sunzenshen
  linkedin: alan-shen/14/7b6/325
  bio: "Hello, my name is Alan, and I am a recovering code hoarder. There’s always so much to learn, and this little corner of the internet seems like a good place as any to organize my thoughts."
  email_md5: cff533d440dad4c74d1603d3141f1ee3

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:
