# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 20 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: "@sunzenshen"

title: "Alan Shen"
description: Pardon the dust.
images: //sunzenshen.github.io/images/
author:
  name: Alan Shen
  email: sunzenshen@gmail.com
  github: sunzenshen
  twitter: sunzenshen
  linkedin: sunzenshen
  bio: "Software Engineer In Colorful Colorado"
  email_md5: cff533d440dad4c74d1603d3141f1ee3

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

gems:
  - jekyll-paginate
